[package]
name = "pmg-log-tracker"
version = "3.0.1"
authors = ["Mira Limbeck <m.limbeck@proxmox.com>", "Dietmar Maurer <dietmar@proxmox.com>"]
edition = "2021"
license = "AGPL-3"
description = "Proxmox Mailgateway Log Tracker. Tool to scan mail logs."
homepage = "https://www.proxmox.com"

exclude = [ "build", "debian" ]

[dependencies]
anyhow = "1"
flate2 = "1.1"
libc = "0.2"
proxmox-time = "2.1"
pico-args = { version = "0.5", features = ["combined-flags"] }
