overlay = "."
crate_src_path = ".."
maintainer = "Proxmox Support Team <support@proxmox.com>"

[source]
section = "admin"
homepage = "https://www.proxmox.com"
vcs_git = "git://git.proxmox.com/git/pmg-log-tracker.git"
vcs_browser = "https://git.proxmox.com/?p=pmg-log-tracker.git;a=summary"
build_depends = ["faketime"]

[package]
summary = "Proxmox Mailgateway Log Tracker"
description = "Tools to scan mail logs"
