overlay = "."
crate_src_path = ".."

[source]
maintainer = "Proxmox Support Team <support@proxmox.com>"
section = "admin"
homepage = "http://www.proxmox.com"
vcs_git = "git://git.proxmox.com/git/pmg-log-tracker.git"
vcs_browser = "https://git.proxmox.com/?p=pmg-log-tracker.git;a=summary"

[package]
summary = "Proxmox Mailgateway Log Tracker"
description = "Tools to scan mail logs"
